### PR TITLE
Make Signal on-boarding user-friendly

### PR DESCRIPTION
**Pull request by archie94**
- have a callback mechanism for every signal operations

Signed-off-by: Arka Prava Basu <arkaprava94@gmail.com>

### CODE REVIEW

**Comment by archie94** [comment]
- Registration and Verification will now show a toast denoting success or failure (Better UI required to denote the procedure(s) are running in background)
- For all other Signal communications request and result are logged.

**Comment by n8fr8** [comment]
looking good...

**Comment by archie94** [comment]
Have introduced a new flag to track Signal number verification. This is hopefully provide better clarity to users on the state of their Signal on-boarding.

Have added an option to wipe out Signal setup. This will help users to restart their on-boarding process without having to do a clear app data / re-install.

The downside is on an app upgrade we have no way of identifying whether Signal is setup successfully (registered and verified). We may need to ask the ones updating their app to Reset Signal configuration and on-board again. :/

**Comment by archie94** [comment]
Further scopes of improvement:
- show better failure msg when Signal registration or verification fails.

This is require changes in signal-cli lib. Will pick this up in a separate PR!

**Comment by n8fr8** [comment]
@archie94 thanks for all the excellent work on this!

**Pull request merged**
