### PR TITLE
Video monitoring

### PR DESCRIPTION
**Pull request by percy-g2**
https://github.com/guardianproject/haven/issues/164

### CODE REVIEW

**Comment by n8fr8** [comment]
When is the video monitoring triggered? Can you explain more about how you see this working?

**Comment by percy-g2** [comment]
when ever there is a change in pixels of last image and current , it triggers recording event (same as capture image event) with the length configured from settings( by default it is 30 secs of recording).
Note: if video monitoring is enabled i disable the audio recording service as recording uses audio source.(to avoid conflict)

**Comment by n8fr8** [comment]
Testing, reviewing now!

**Comment by n8fr8** [comment]
Works good enough to merge! I re-enabled audio recording, since we need to support that if there is off-camera sound made. We'll need to improve the logic to check if audio recording is already underway, and if so, don't trigger videorecording, and vice versa.

**Pull request merged**
