### PR TITLE
Fix crash due to missing resource on API levels 20 and below

### PR DESCRIPTION
**Pull request by TheDorkKnightRises**
See issue #90 

Tested on Android 4.4.2

### CODE REVIEW

**Comment by fat-tire** [comment]
FWIW I also addressed this issue in PR #67 by just reusing an existing forward arrow image used elsewhere (as a .png).  I did notice a problem with the XML vector graphic disappearing from the actual apk in my build and not being accessible -- at least from api 16 and figured using the existing image worked just as well.  Didn't investigate why the arrow xml image got dropped by the latest Android Studio tho.

**Comment by fat-tire** [comment]
I should add that I did try stuff like explicitly saying to keep the resource w a res/values/keep.xml and turning on legacy vector image support (also in #62) but it didn't seem to matter... might be an AS bug.

**Comment by TheDorkKnightRises** [comment]
Wait so your fix works well on all older devices too? Then I should probably close this PR, cuz I just dug out a very old Samsung Galaxy Ace running a custom 4.4.2 ROM and for some reason it's crashing  due to 
`org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector`, even though I tested it on an old HP VoiceTab 7 running 4.4.2 before submitting the PR (yeah, I've been digging out all my old devices for testing out Haven 😛 )
I was currently in the process of making most of the same changes I see in your PR #67 like updating the SDKs and build tools and setting `vectorDrawables.useSupportLibrary = true`, to try and fix it, but if you've already fixed it and it's just waiting to be merged, then it's redundant

**Comment by fat-tire** [comment]
Yes after trying the things you tried I realized there was already a forward arrow image included in the app as a forward arrow- so I just used that.  the invalid drawable xl is probably the file is missing..  you can check by inspecting the apk in AS and probably will find it's missing.  This seems to be some kind of AS bug.  See if my PR fixes it and do report back!

**Comment by TheDorkKnightRises** [comment]
Just tested your updateproj branch on both my API19 devices as well as my primary device running Oreo 8.1, works fine 👍 
(Well, did find an issue with initializing the camera on the Galaxy Ace, but that's not related to this matter... will probably create a separate issue tomorrow after checking if a similar case has not already been reported)

**Comment by TheDorkKnightRises** [comment]
Issue fixed in #67

**Pull request closed without merging**
