### PR TITLE
for #365 reduce camera resolution and remove one unneeded bitmap

### PR DESCRIPTION
**Pull request by n8fr8**

### CODE REVIEW

**Comment by archie94** [comment]
With the default motion detection sensitivity threshold performance is better on this branch. However reducing the threshold to something around 948 I am still running into ANRs. :/

**Comment by n8fr8** [comment]
... but no OOMs?

**Comment by archie94** [comment]
Faced OOMs too! Will provide the crashlog in some time.

**Comment by n8fr8** [comment]
This latest commit should vastly simplify the processing going on during motion detection. The problem was really in the whole overlay bitmap UI generation. That UI is fun, but not that usable. I am now just displaying a simple string "motion detection" to indicate a match.

This is part of new work on showing more of an interactive display for all sensor matches, like "Sound Detected" or "Device Moved" etc, so that you can see in one view all of the various sensor states.

**Comment by archie94** [comment]
Can confirm! No more ANRs or OOM errors 👍 !

However the number of Triggers of type Motion(Camera) is significantly reduced. Is this intended?

**Comment by archie94** [comment]
```
However the number of Triggers of type Motion(Camera) is significantly reduced. Is this intended?
```

Preliminary testing. Would be great if someone can cross-verify.

**Comment by lukeswitz** [comment]
On it

**Comment by lukeswitz** [comment]
Notes: Getting a crash using camera on nexus 4 & 5 (AOS 5&6), with the monitor continuing in the background. Less frames could benefit the load on notifications. Without the overlay it's very hard to use sensitivity config.
```

  --------- beginning of crash
02-08 17:46:10.367 26412-26412/org.havenapp.main E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.havenapp.main, PID: 26412
    java.lang.IllegalStateException: Fragment CameraFragment{258a9de5} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:696)
        at androidx.fragment.app.Fragment.getResources(Fragment.java:760)
        at androidx.fragment.app.Fragment.getString(Fragment.java:782)
        at org.havenapp.main.ui.CameraFragment$1.handleMessage(CameraFragment.java:56)

```

**Comment by n8fr8** [comment]
@lukeswitz I found and fixed that crash.

Otherwise, going to finish this up, and then work on improving tuning and feedback UI in another PR.

**Pull request merged**
