### PR TITLE
Delete all events log fab button and bug fix.

### PR DESCRIPTION
**Pull request by percy-g2**
* Set empty view visibility to visible when event list is empty after deleting events.
* [Feature] Delete all events log.

### CODE REVIEW

**Comment by percy-g2** [comment]
screenshot_20180103-000904
screenshot_20180103-000858

**Comment by n8fr8** [comment]
Perhaps we can put the "delete all" as a menu option for now? It is confusing to have two fab buttons.

**Comment by percy-g2** [comment]
I won't prefer that as a user, going to menu then selecting it and confirming the deletion action.
we can take more opinion about this from other contributors.

**Comment by percy-g2** [comment]
Progress dialog look more neat. screenshot_20180106-052412

**Comment by pk-development** [comment]
I would have went with a long press on a listview item to give a dialog to delete current event or delete all, I personal would like to delete at source rather than having to go into settings to delete.

**Comment by n8fr8** [comment]
Many thanks for your work on this. We went with a simpler, newer PR that provides a menu option.

**Pull request closed without merging**
