### PR TITLE
Google Email Alerts, Bug Fixes and Improvements.

### PR DESCRIPTION
**Pull request by percy-g2**
* Event Trigger Google Email Alerts with attachments.
* Fix Settings EditTextPreference input type number not showing( use workaround)
* No need to set summary %s handles summary from value string array automatically.
* Set country code Phone number and Signal Number.
* Fix UI for set delay timer dialog.

### CODE REVIEW

**Comment by percy-g2** [comment]
screenshot_20180102-112633
screenshot_20180102-112609
screenshot_20180102-112536

**Comment by fat-tire** [comment]
So these look like interesting features-- and I don't make the decisions or anything,  but I do have some questions, particularly as to all the unrelated stuff crammed into these commits that make it very difficult to read/understand.  Given the unknown libraries I didn't want to just run it, but from eyeballing it a few things popped to mind:

Re:  the preference changes:

1.  Why go off the standard preference support library with this takisoft version?  What is the bug that this is addressing?  I wasn't clear on that.
2.  This is just a thought here but I'd wait to add the lambdas to a single pass for all the files across the whole app rather than doing it bit-by-bit (same with replacing LEFT with START, reordering xml, etc. shouldn't these be in their own individual lint-commits rather than mixed in with everything else?)
3.  Instead of adding extra [commits](https://github.com/guardianproject/haven/pull/179/commits/cd7476f5b24fd19855da4cd374dc4ebc0ed4b993) that clean up mistakes, why not squash/combinethem into a single commit that  includes the changes.
4.  Reading quickly here (I haven't tried building this), but what is `!getCountryCode().equalsIgnoreCase(signalNum))` for?   Does [this](https://github.com/percy-g2/haven/blob/4826ec762bfe3f752d7379cadd38449ada42e2e2/src/main/java/org/havenapp/main/SettingsFragment.java#L294) check the WHOLE # against the country code?  Shouldn't it just check the beginning?  Also, why?  In some countries (US for example) there the +1 is optional.  (1 is optional as well).  (Sorry if I'm missing this- like I said I haven't run it, just reading it...)
5.  never seen this before:  `android:summary="%s` --  does that really work?!  Might want to at least label the front/back/none w/a comment tho because 0, 1, 2 isn't as readable.

re: the gmail thing

1.  The jars added [here](https://github.com/guardianproject/haven/pull/179/commits/987ec4da2cda893cf2f7227284439b2fb73961d2).  Where is the source for these?  Why aren't they being built?  Are they GPLv3 compatible?  Why is "[additional](https://github.com/percy-g2/haven/blob/987ec4da2cda893cf2f7227284439b2fb73961d2/src/main/jniLibs/additionnal.jar)" spelled like that?
2.  Same note as above re the lint and lambda stuff-- I've been trying to [cleanly separate them](https://github.com/guardianproject/haven/pull/151) (but it's already been broken so I guess that was pointless).   It makes it really hard to see what you're actually doing in this commit vs. all the random moving methods around and changing indenting and stuff.  More than half of this commit has nothing to do with the email stuff, which doesn't start until line 108... I think.  Can't you just `git gui` or `git -i` and only select those lines that are _actually_ necessary for the commit?  There are dozens of changes here that have zero to do with adding the gmail stuff.
3.  Why [this](https://github.com/guardianproject/haven/pull/179/commits/d8ae1b1b95b42340eed81c237acde1bac46ccc8e#diff-0a77d5b930fb5d01263a5a47e325c9f9R132) assertion?  Maybe it's effectively/better be done with a [@NonNull](https://developer.android.com/reference/android/support/annotation/NonNull.html)?  Not sure what's up here.
4.  More strange spelling:  `setMaillPassword`.

(I had to stop reading this about 1/3 down as it was taking a long time to wade through all the irrelevant edits to find what was a legit change.  I write illegible messes myself all the time so I shouldn't complain here, but I'm pretty sure your commits can be 1/4-1/8th the size each and much more readable if you left out the whitespace changes, the moving methods around, the Java 8 changes, etc. and kept it to the stuff that this commit actually does.)

**Comment by mig5** [comment]
+1 on the above, it is not my project but being a rather high profile privacy-related project, the binary blobs especially make me nervous

I saw this PR arrive roughly real-time as just misc fixes, and then some hours later suddenly added all the Gmail stuff (and jar blobs) which would’ve been better as a separate PR IMO just for clarity

**Comment by leonardoporpora** [comment]
Is possible to send GPG encrypted mail? Is Gmail the only email provider that we can use?

**Comment by pk-development** [comment]
If for any reason a malicious person was to get the device is it possible to extract the email password from that app then access the email account? If so they could just delete all traces of what was sent, they could close the account, maybe get the number used to create the account.

Good idea but there could be alot of security issues with it.

You'd have to use a new email just for the app and use burner phone number to verify.

**Comment by percy-g2** [comment]
https://github.com/Gericop/Android-Support-Preference-V7-Fix
https://code.google.com/archive/p/javamail-android/downloads
https://code.google.com/archive/p/javamail-android/source/default/source


@fat-tire 

Have a look into above links.

1. When you open edit text preference for phone number and signal number , even though it's number input type keyboard opens in text layout.
2.  never seen this before: android:summary="%s" -- does that really work?! Might want to at least label the front/back/none w/a comment tho because 0, 1, 2 isn't as readable.  https://developer.android.com/reference/android/preference/ListPreference.html#getSummary%28%29
3. !getCountryCode().equalsIgnoreCase(signalNum)) that check is for not setting country code alone the phone number if user doesn't save the number.
4. Yeah i agree lint commits should be squashed but as @n8fr8 mentioned in one of his comments to not push large lint changes.

**Comment by pk-development** [comment]
@percy-g2 Cool, good work👍

**Comment by n8fr8** [comment]
Thanks for all the work @percy-g2 and for the review @fat-tire. I agree that this one PR is way too dense and encompasses too much. In particular, the Gmail/Email feature alone, needs to be separated out and discussed as its own feature. As it stands, I don't think we can accept it, since it relies on the user entering in a password. I know it is annoying to do so much work and not have it accepted, but we have to be more careful with this project than most. Please keep at it, and find a way to break up your work into smaller pieces, and do a little bit at a time.

**Comment by percy-g2** [comment]
@n8fr8 sure, will break up into small PR's.

**Comment by pk-development** [comment]
@percy-g2 I second what @n8fr8 is saying and don't give up the PR's. Your work is great so I wouldn't get pissed off. Maybe some sort of IRC would useful to point devs in the right direction as to what is needed and also to make sure another dev is not working on the same issue.

**Pull request closed without merging**
