### PR TITLE
Android Pie + jetpack + androidx + compat + modern build + more !

### PR DESCRIPTION
**Pull request by fat-tire**
androidx all the things!

I am submitting this PR for testing & improvement.  This submission:

* Brings the build up to date for the very latest:
-- Android Studio 3.3 Canary + build tools
-- gradle 4.10.2
-- Jetpack/androidx support libraries
-- more Compat support code
-- theme related stuff for newer MateriaComponents-based theme (instead of AppCompat).
-- other build related changes (requests a required permission in Pie, simplifies build.gradle, uses Jetifier, etc.)
* Fixes a few lint issues & removes a tiny bit of dead code/cleanup stuff
* Fixes a missing table bug described in bug #333 (not a fix to that issue though)
* Keeps a few NPEs from taking down the app
* Some other stuff which is detailed in the commit description (and of course is in the code itself)
* Updated all the external 3rd-party libraries that could be updated and not break anything

The above stuff is broken into a few different commits but I think they can be taken as a whole.

What I've tested this on:

- The emulator api28
- A nVidia Shield tablet running an ancient cyanogenmod

That's it.  No really, that's it.  Did I check the signal notification stuff?  Nope.  Did I try it on dozens of systems to make sure it never crashed?  Nawp.  No promises or guarantees-- I'm relying on some outside testing (that's you, the person reading this) to validate stuff works and fix it if it doesn't.  Stuff may have broken that I just didn't catch, but even this is the case, I think this is a starting point that should help save some time moving forward.

Because of all the big changes, it might be a good idea to invalidate caches/restart AS before building.

Cheers
ft

### CODE REVIEW

**Comment by fat-tire** [comment]
To not fail the checks, someone's gotta accept the license for package Android SDK Build-Tools 28.0.3!

ft

**Comment by n8fr8** [comment]
Got it and thanks!

**Comment by n8fr8** [comment]
So far so good on this, but pinning to the AppIntro master has caused some UI glitches due their code being in progress.

**Comment by fat-tire** [comment]
Hmm.  I didn't notice any glitches myself, but I pinned to master on AppIntro since that's where they migrated to androidx.  It's possible that the older version will work w/Jetifier I can't remember if I ran into an issue w/that, which is why I switched to master... or whether I just figured "hey they migrated over, so I'll use that.."  But regardless, feel free to modify this to whatever works for you.  I just had some time so figured I'd put it all together.

Also, if the UI glitches are related to the button styling-- that may be my adjustments to the [slide layouts](https://github.com/guardianproject/haven/pull/350/files#diff-47523eafff913e065803c22211bcaa12) or overriding the [done button layout](https://github.com/guardianproject/haven/pull/350/files#diff-5d1b597d2e4a23d8bcc86614a155153b).  I was playing with this to make it look better for my tablet, but if you want to change them back or whatever, go for it :)  Also I think I needed to override the layout for the button so that it was using AppCompatButton (otherwise the background was filled in with yellow rather than just the outline)...

Anyway, I'll let you take this PR from here.  Make whatever changes you feel appropriate... Thanks for trying it out!

**Comment by fat-tire** [comment]
The RTL/LTR direction code was changed [here](https://github.com/apl-devs/AppIntro/commit/21d739578adb5e33a13b0f38e1599b3c4fac35e6)... does reverting (or pinning to version prior to this commit) fix it?

Also found [this issue](https://github.com/apl-devs/AppIntro/issues/547).

**Comment by n8fr8** [comment]
For now, since we don't have RTL localizations, I will just set supportsRtl to false.

**Pull request merged**
