### PR TITLE
Remove sms support

### PR DESCRIPTION
**Pull request by archie94**
Aims to solve #364 

Changes

- Removed `SEND_SMS` permission -> removed remote SMS notification feature.
- On Settings the Switch for enabling SMS and Signal notifications now only enables remote notification through Signal.
- on enabling the Switch we collect data required for remote notification ( a remote phone number, a verified signal phone number)
- the String for the Switch name has been edited, we need to update translations for the same.

Some thoughts:

- During on-boarding we may need to add a note to complete the Signal integration since having a remote number will not enable notification. IMO the Signal integration process is not very intuitive and can be further streamlined.

### CODE REVIEW

**Comment by lukeswitz** [comment]
Thanks for all the work on this. Forced adoption of Signal isn’t all bad, but it can be improved. 

Did a small, hands-on workshop  w/this branch yesterday; group of ten users. Signal & encrypted messaging was discussed & demonstrated followed by Haven. 

*Users w/no prior knowledge of Haven 

- 4/10 reported using Signal semi regularly/regularly. 
- 10/10 had a paint point in onboarding, configuring sensors.
- 2/10 had problems trying to link signal. (Resolving was not simple, required emptying fields and restarting activities.)
- 10/10 asked if two signal numbers are required
- 5/10 said they’d use the app as is and enjoyed the experience. 
- 4/10 said they would use the app if Signal was not required. 
- 1/10 would not use this app in the future.

This is a tiny sample size from a tech-forward city. It did however contrast basic:advanced users and how they fell about learning two apps at the same time. 

- Users that understood encryption were highly receptive to using/registering Signal. 

- Some crashes were found when remote number is used without proper verification. Overall, better feedback than expected. 

C’mon, Google, do the right thing.

**Comment by archie94** [comment]
Some very insightful metrics there. Signal verification flow needs some UX improvements. Right now there is no way to tell whether verification is a success or failure. In the coming week will dig into the signal-CLI and see if something can be done.

**Comment by n8fr8** [comment]
Yes, a basic step through Signal onboarding setup, explaining how to verify, would be helpful. We also need to explain the concept of whether you need a second "virtual" phone number or not.

One idea I had was to see if Signal was installed on the phone or not. If not, then just go ahead using the device's built in phone number. Otherwise, we can show a screen that says "Looks like you are already using Signal on here. You'll need to get a second number, and here is how."

**Comment by n8fr8** [comment]
No progress from Google contacts. Going to merge this, and then figure out a way to keep SMS as an option through an external APK of some kind, or perhaps a flavored build for F-Droid / APK download.

**Pull request merged**
