### PR TITLE
Don't keep in portrait mode

### PR DESCRIPTION
**Pull request by percy-g2**
this will handle the changes in orientation and preserve data after it.

### CODE REVIEW

**Comment by opticod** [comment]
Orientation of `AccelConfigureActivity` & `MicrophoneConfigureActivity` - had been kept portrait, because it will be convenient for users to slide the wheel to change detection threshold and to see the graph at the same time as discussed in Issue #100 and fixed in #101

**Comment by percy-g2** [comment]
I won't recommend keep the screen in fixed layout,
Better to handle the UI

**Comment by opticod** [comment]
So you mean different UI design layouts for portrait and landscape ? ...Sounds good

**Comment by fat-tire** [comment]
what about when running on a Chromebook which is usually in landscape?  Are you anticipating that the orientation would change while setting the accelerometer sensitivity?  if so, maybe it should just "lock" to whatever orientation it starts at?

**Comment by percy-g2** [comment]
no using weights we can handle it on any orientation and screen size. check my modified UI with weights
device-2017-12-29-231320
device-2017-12-29-231515

**Pull request merged**
