### PR TITLE
add largeHeap true for Prevent OutOfMemoryError OOM

### PR DESCRIPTION
**Pull request by FREEWING-JP**
OutOfMemoryError OOM createBitmap MotionAsyncTask.java:118

Samsung Galaxy S5 (Japan au/KDDI SCL23, OS 4.4.2)
When detect camera motion has changed . Occur OutOfMemoryError OOM .
So I add largeHeap="true" to AndroidManifest.xml .

Error Log
 E/art(17333): Throwing OutOfMemoryError "Failed to allocate a 8294412 byte allocation with 7418352 free bytes"
 E/AndroidRuntime(17333): FATAL EXCEPTION: Thread-1638
 E/AndroidRuntime(17333): Process: org.havenapp.main, PID: 17333
 E/AndroidRuntime(17333): java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 7418352 free bytes
 E/AndroidRuntime(17333):  at android.graphics.Bitmap.nativeCreate(Native Method)
 E/AndroidRuntime(17333):  at android.graphics.Bitmap.createBitmap(Bitmap.java:924)
 E/AndroidRuntime(17333):  at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
 E/AndroidRuntime(17333):  at android.graphics.Bitmap.createBitmap(Bitmap.java:833)
 E/AndroidRuntime(17333):  at org.havenapp.main.sensors.media.MotionAsyncTask.run(MotionAsyncTask.java:118)

### CODE REVIEW

**Comment by n8fr8** [comment]
Usually the answer to these issues is to fix the code that is attempting to use too much memory. Perhaps, when we set the camera image size, we should take into, or somehow, test for available memory.

**Comment by FREEWING-JP** [comment]
Yes, I also agree with the opinion of "the most answer to these issues is to fix the code" .
The solution of largeHeap is easygoing way of thinking .
However, it is concise as a countermeasure .

I am in the opinion when modifying the code .
That is, the image used for camera difference detection is too high resolution (Overspec).
The image of the event record needs high resolution .
But, I think that the resolution of the difference detection is enough for medium resolution .

**Comment by FREEWING-JP** [comment]
Another way Add catch OutOfMemoryError exception and Garbage Collection retry
(Yes . It is also easygoing way of thinking .)

MotionAsyncTask.java line 117~
```
	// Rotating Bitmap
//	rawBitmap = Bitmap.createBitmap(rawBitmap, 0, 0, width, height, mtx, true);
	try {
		rawBitmap = Bitmap.createBitmap(rawBitmap, 0, 0, width, height, mtx, true);
	} catch(OutOfMemoryError e) {
		// Garbage Collection
		java.lang.System.gc();
		// Retry
		rawBitmap = Bitmap.createBitmap(rawBitmap, 0, 0, width, height, mtx, true);
	}
```

**Comment by pk-development** [comment]
This is a very common problem in Android and you have to cache the images to avoid an OOM error. Calling the java.lang.System.gc(); does not guarantee the the Garbage collector will free the resources on the heap so not good practice. The large heap won't fix this issue either I've tried that on another project before:-)

**Comment by n8fr8** [comment]
unfortunately @pk-development in this case, we can't cache, since the OOM issues relates to the frames we are pulling off the camera preview to power the visual motion detection. We just need to be more sane about the resolutions we are setting for the previews on limited memory devices.

**Comment by n8fr8** [comment]
Whether we show it or not, we still have to grab the frame. We are really trying to find the best way to balance the resolution of the image vs the speed we can process each frame. There was some good points in this thread stating that the detect resolution can be low, but then that can trigger the capture image higher resolution photo... so we may just push the preview res down, and up the capture res.

**Comment by n8fr8** [comment]
Also @pk-development for the list view, we're already using Picasso which handles cacheing and efficient loading.

**Comment by n8fr8** [comment]
Okay, well, for now, we can accept the largeHeap option, and then I may open another ticket/issue to work on the improvement of the motion detection code.

**Pull request merged**
