### PR TITLE
Update project/libraries/tools/Java to latest stable & fix breakage on older APIs

### PR DESCRIPTION
**Pull request by fat-tire**
Tested on my real device w/7.1 and emulator w/API 16.  Seems to work, but of course YMMV.

### CODE REVIEW

**Comment by fat-tire** [comment]
Note the autobuild failed because:

> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27, Android SDK Build-Tools 27.0.3].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.

So not my fault :+1:

**Comment by n8fr8** [comment]
Yeah, we need to update our travis config to match the new SDK. Will do that, test and then merge. Thanks!

**Comment by fat-tire** [comment]
Two quick updates, as you can see here:

(1) it still seems to build/run fine when we update to Java 8, and
(2) A crash related to the new requirement for a notification channel in Oreo is also fixed.

Still appears to run alright in the API 16 emulator, but please double-check!

**Comment by n8fr8** [comment]
Awesome work. Eager to test, but will have to wait until after Christmas. We'll get our travis build update, as well.

**Comment by n8fr8** [comment]
Reviewing and testing now...

**Pull request merged**
