### PR TITLE
Dutch Translation

### PR DESCRIPTION
**Pull request by JayJay1989**

### CODE REVIEW

**Comment by n8fr8** [comment]
Are you going to translate the actual words as well?

**Comment by JayJay1989** [comment]
Something went wrong, ill do a new request when im home.

**Comment by JayJay1989** [comment]
Dutch updated

**Comment by n8fr8** [comment]
Hmmm, this isn't the right approach either. Perhaps you should use Transifex web interface to provide the translation?

https://www.transifex.com/guardianproject/haven/dashboard/

**Pull request closed without merging**
